# Theme settings
dox:
    baseurl: /CV
    title: Project Name
    theme_color: '#0976f8' # Define theme primary color with HEX value
    language: en-US # Use ISO language and country codes to setup language of your website - https://www.w3schools.com/tags/ref_language_codes.asp and https://www.w3schools.com/tags/ref_country_codes.asp
    header:
        logo:
            text: Portfolio
            image:
       
        nav:
            - item_name: Homepage
              item_url: /
            - item_name: Projects
              item_url: /projects
            # - item_name: Toolkit
            #   item_url: /projectmantoolkit
        # cta:
        #     label: Projects
        #     url: /weeknotes
        #     icon: folder # Choose from 266 icons in "Feather" icon set, list of all icons is available here - https://feathericons.com
    footer:
        logo:
            text: John Ferguson
            image:
        text: Copyright &copy; 2022. - Portfolio <br>All rights reserved.
    google_analytics:
        tracking_code: G-J7DK0PHS1Q # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your Disqus forum shortname to activate comments site-wide

# Defining collections
collections:
    documentation:
        output: true

# Defining defaults
defaults:
    -
        scope:
            path: ''
            type: 'documentation'
        values:
            layout: 'documentation-single'

# SASS settings
sass:
    sass_dir: ./dox-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./dox-theme/_layouts
includes_dir: ./dox-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
